graph/urls.py
from django.urls import path
from . import views

app_name = 'graph'

urlpatterns = [
    # /graph/
    path('', views.index, name='index'),

    # /graph/register/
    path('register', views.register, name='register'),

    # /graph/login/
    path('login', views.login_user, name='login'),

    # /graph/logout
    path('logout_user', views.logout_user, name='logout_user'),

    # /graph/plot/
    path('plot', views.plot, name='plot'),

    # /graph/shares/
    path('shares', views.advanced, name='advanced'),

    # /graph/pnl/
    path('pnl', views.pnl, name='pnl'),

    # /graph/backtest/
    path('backtest', views.backtest, name='backtest'),

    # /graph/backtest2/
    path('backtest2', views.backtest2, name='backtest2'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('graph/', include('graph.urls')),
]

graph/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

graph/forms.py
from django.contrib.auth.models import User
from django import forms

class ContactForm(forms.Form):
    alpha = forms.CharField(label='alpha', max_length=100)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

graph/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from random import randrange

from .forms import ContactForm, UserForm
from django.contrib.auth.models import User

from graph.backtest import *


# Create your views here.
def index(request):
    template = loader.get_template('graph/index.html')
    context = {}
    return HttpResponse(template.render(context, request))

def plot(request):
    context = {}
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            global values2, values3, header2, header3, data_for_x, data_for_y
            alpha = form.cleaned_data['alpha']
            [data_for_x, data_for_y, values, values2, values3, header2, header3] = plot_graph(str(alpha))
            data_for_x = [str(date) for date in data_for_x[0:len(data_for_y)]]
            return render(request, 'graph/index.html', {
            'form': form,
            'alpha': alpha,
            'data_for_x': data_for_x,
            'data_for_y': data_for_y,
            'values': values,
            'values2': values2,
            'values3': values3,
            })

def backtest(request):
    template = loader.get_template('graph/backtest.html')

    textarea ="""
    Enter long position on 2016-07-11 Quantity: 40 at 458.0 \n
    Exit long position on 2016-07-22 Quantity: 40 at 454.8 PNL: -128.0 in 9 days\n
    Enter long position on 2016-07-25 Quantity: 40 at 464.6\n
    Exit long position on 2016-10-17 Quantity: 40 at 531.0 PNL: 2656.0 in 55 days\n
    Exit short position on 2016-11-15 Quantity: 12 at 483.0 PNL: -1189.8 in 178 days\n
    Enter short position on 2016-11-29 Quantity: 12 at 454.0\n
    Enter long position on 2017-01-02 Quantity: 40 at 453.05\n
    Exit long position on 2017-02-28 Quantity: 40 at 504.6 PNL: 2062.0 in 39 days\n
    Enter long position on 2017-03-01 Quantity: 40 at 510.0\n
    Exit long position on 2017-03-03 Quantity: 40 at 500.0 PNL: -400.0 in 2 days\n
    Enter long position on 2017-03-07 Quantity: 40 at 509.0\n
    Exit long position on 2017-04-17 Quantity: 40 at 517.3 PNL: 332.0 in 26 days\n
    Enter long position on 2017-04-21 Quantity: 40 at 536.85\n
    Exit long position on 2017-04-25 Quantity: 40 at 526.5 PNL: -414.0 in 2 days\n
    Enter long position on 2017-04-26 Quantity: 40 at 528.0\n
    Exit long position on 2017-05-02 Quantity: 40 at 527.5 PNL: -20.0 in 3 days\n
    Enter long position on 2017-05-03 Quantity: 40 at 536.0\n
    Exit long position on 2017-05-04 Quantity: 40 at 530.0 PNL: -240.0 in 1 days\n
    Exit short position on 2017-05-10 Quantity: 12 at 496.0 PNL: -504.0 in 110 days\n
    Enter long position on 2017-05-12 Quantity: 40 at 543.7\n
    Enter short position on 2017-05-12 Quantity: 12 at 543.7\n
    Exit long position on 2017-05-17 Quantity: 40 at 522.6 PNL: -844.0 in 3 days\n
    Enter long position on 2017-05-18 Quantity: 40 at 517.0\n
    Exit long position on 2017-05-19 Quantity: 40 at 517.0 PNL: 0.0 in 1 days\n
    Enter long position on 2017-05-30 Quantity: 40 at 521.8\n
    Exit long position on 2017-06-01 Quantity: 40 at 515.6 PNL: -248.0 in 2 days\n
    Enter long position on 2017-06-02 Quantity: 40 at 527.0\n
    Exit long position on 2017-06-07 Quantity: 40 at 519.0 PNL: -320.0 in 3 days\n
    Enter long position on 2017-06-09 Quantity: 40 at 521.5\n
    Exit long position on 2017-06-13 Quantity: 40 at 517.5 PNL: -160.0 in 2 days\n
    Exit short position on 2017-06-28 Quantity: 12 at 490.0 PNL: 644.4 in 32 days\n
    Enter short position on 2017-07-06 Quantity: 12 at 502.0\n
    Enter long position on 2017-07-10 Quantity: 40 at 494.7\n
    Exit long position on 2017-08-11 Quantity: 40 at 517.0 PNL: 892.0 in 24 days\n
    Exit short position on 2017-08-14 Quantity: 12 at 509.2 PNL: -86.4 in 27 days\n
    Enter short position on 2017-08-29 Quantity: 12 at 518.4\n
    Enter long position on 2017-09-04 Quantity: 40 at 523.0\n
    Exit long position on 2017-09-05 Quantity: 40 at 522.0 PNL: -40.0 in 1 days\n
    Enter long position on 2017-09-13 Quantity: 40 at 534.1\n
    Exit long position on 2017-09-25 Quantity: 40 at 520.25 PNL: -554.0 in 8 days\n
    Exit short position on 2017-10-18 Quantity: 12 at 490.1 PNL: 339.6 in 35 days\n
    """

    context = {}
    return HttpResponse(template.render(context, request))

def backtest2(request):
    Alpha1 = 'mean_sma(-(delta(c,5)/delay(c,5)-cs_mean(delta(c,5)/delay(c,5))),5)'
    Alpha2 = 'c'
    Alpha3 = '-c'
    Alpha4 = 'o-c'
    Alpha5 = 'c-o'
    alphas = [Alpha1, Alpha2, Alpha3, Alpha4, Alpha5]
    random_index = randrange(0,len(alphas))
    [data_for_x, data_for_y, values, values2, values3, header2, header3] = plot_graph(str(alphas[random_index]))
    template = loader.get_template('graph/backtest2.html')
    data_for_x = [str(date) for date in data_for_x[0:len(data_for_y)]]
    context = {
    'data_for_x': data_for_x,
    'data_for_y': data_for_y,
    }
    return HttpResponse(template.render(context, request))

def advanced(request):
    return render(request, 'graph/shares.html', {
    'values2': values2,
    'header2': header2,
    })

def pnl(request):
    return render(request, 'graph/pnl.html', {
    'values3': values3,
    'header3': header3,
    })


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('graph:index')
    context = {
        "form": form,
    }
    return render(request, 'graph/register.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                user = User.objects.get(username=username)
                return render(request, 'graph/index.html', {'user': user})
            else:
                return render(request, 'graph/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'graph/login.html', {'error_message': 'Invalid login'})
    return render(request, 'graph/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'graph/index.html', context)

graph/templates/graph/backtest.html
<head>
  <!-- Plotly.js -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.jquery.min.js"></script>
  <link href="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.min.css" rel="stylesheet"/>

</head>

<style>

  /* Style The Dropdown Button */
  .dropbtn {
    background-color: black;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
    margin-left: 600px;
  }

  /* The container <div> - needed to position the dropdown content */
  .dropdown {
    position: relative;
    display: inline-block;
  }

  /* Dropdown Content (Hidden by Default) */
  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
    margin-left: 600px;
  }

  /* Links inside the dropdown */
  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }

  /* Change color of dropdown links on hover */
  .dropdown-content a:hover {
    background-color: black;
    color: white;
  }

  /* Show the dropdown menu on hover */
  .dropdown:hover .dropdown-content {
    display: block;
  }

  #button_advanced {
    background-color: black;
    border: none;
    color: #EBC1EE;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
    margin: auto;
  }

  #button_advanced:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  }

  /* Add a black background color to the top navigation */
  .topnav {
    background-color: black;
    overflow: hidden;
    min-width: 1000px;
  }

  /* Style the links inside the navigation bar */
  .topnav a {
    float: left;
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
    font-family: Arial;
  }

  /* Change the color of links on hover */
  .topnav a:hover {
    background-color: white;
    color: black;
  }

  /* Add an active class to highlight the current page */
  .active {
    background-color: #EBC1EE;
    color: black;
  }

  /* Hide the link that should open and close the topnav on small screens */
  .topnav .icon {
    display: none;
  }

  #alpha {
    width: 600px;
    height: 40px;
    border-width: 2px;
    border-color: black black black black;
    margin: auto;
  }

  #submit {
    width: 600px;
    background-color: black;
    border: none;
    border-color: #8F1383;
    color: white;
    height: 40px;
    margin-left: 80px;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }

  #submit:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  }

  .container {
    position: relative;
    overflow: hidden;
    float: left;
  }

  #left {
    display: inline-block;
    float: left;
  }

  #myDiv {
    display: inline-block;
    float: right;
    margin: auto;
    overflow: hidden;
  }

  #table {
    display: inline-block;
    margin: auto;
    border-color: #ad1b9e;
    overflow: hidden;
    border-color: black;
    border-width: 2px
  }

  p.ex1 {
    max-width: 600px;
    max-height: 400px;
    overflow-y: scroll;
    margin-left: 80px;
    background-color: #82CFFD;
}

</style>

<div class="topnav" id="myTopnav">
  <a href="#home">Home</a>
  <a href="#about">About us</a>
  <a href="#create">Create</a>
  <a href="#learn">Learn</a>
  <a href="#faq">FAQ</a>
  {% if user.username %}
    <a href="{% url 'graph:logout_user' %}" style="float:right">Logout</a>
    <a href="#username" style="float:right">{{ user.username }}</a>
  {% else %}
    <a href="{% url 'graph:login' %}" style="float:right">Login</a>
  {% endif %}
</div>

<br><br>

<form action="" method="post">
  {% csrf_token %}
  <select data-placeholder="Choose stocks" multiple class="chosen-select" name="tags">
    <option value=""></option>
    <option>RELIANCE</option>
    <option>HDFCBANK</option>
    <option>TCS</option>
    <option>ITC</option>
    <option>AUROPHARMA</option>
    <option>HDFC</option>
    <option>HUL</option>
    <option>MARUTI</option>
    <option>INFY</option>
    <option>ONGC</option>
    <option>SBIN</option>
    <option>KOTAKBANK</option>
    <option>IOC</option>
    <option>ICICI</option>
    <option>COALINDIA</option>
    <option>LT</option>
    <option>BHARTIARTL</option>
    <option>NTPC</option>
    <option>HCLTECH</option>
    <option>AXIS</option>
    <option>WIPRO</option>
    <option>SUNPHARMA</option>
    <option>VEDL</option>
    <option>ULTRACEMCO</option>
    <option>ASIANPAINT</option>
    <option>INDUSINDBK</option>
    <option>POWERGRID</option>
    <option>TATAMOTORS</option>
    <option>BPCL</option>
    <option>BAJFINANCE</option>
    <option>MM</option>
    <option>BAJAJ_AUTO</option>
    <option>ADANIPORTS</option>
    <option>EICHERMOT</option>
    <option>GAIL</option>
    <option>TATASTEEL</option>
    <option>HEROMOTOCO</option>
    <option>YESBANK</option>
    <option>INFRATEL</option>
    <option>TECHM</option>
    <option>DRREDDY</option>
    <option>HINDPETRO</option>
    <option>BOSCHLTD</option>
    <option>ZEEL</option>
    <option>IBULHSGFIN</option>
    <option>HINDALCO</option>
    <option>AMBUJACEM</option>
    <option>CIPLA</option>
    <option>UPL</option>
    <option>LUPIN</option>
  </select>
  <input type="submit">
</form>


<br><br>

<div class="container">

  <div id="left" class="left">
    <form action="{% url 'graph:backtest2' %}" method="post" id="usrform">
      {% csrf_token %}
      <p>Long Entry&nbsp;&nbsp;<input id="alpha" type="text" name="alpha" placeholder="RSI(c,14)>50"></p>
      <p>Long Exit&nbsp;&nbsp;&nbsp;&nbsp;<input id="alpha" type="text" name="alpha" placeholder="c<0"></p>
      <p>Quantity&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="alpha" type="text" name="alpha" placeholder="40"></p>
      <p>Short Entry&nbsp;<input id="alpha" type="text" name="alpha" placeholder="mean_sma(c,10)<c"></p>
      <p>Short Exit&nbsp;&nbsp;&nbsp;<input id="alpha" type="text" name="alpha" placeholder="RSI(c,14)<35"></p>
      <p>Quantity&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="alpha" type="text" name="alpha" placeholder="10000000"></p>
      <input id = "submit" type="submit" value="Submit">

      <br><br>

    </form>
  </div>

  <br><br>

</div>

    <script>

    $(".chosen-select").chosen({
      width: "40%",
      no_results_text: "Oops, nothing found!",
    });

    </script>
    </div>

<br><br>

graph/templates/graph/index.html
<head>
  <!-- Plotly.js -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<style>

  #button_advanced {
    background-color: #AD1B9E;
    border: none;
    color: #EBC1EE;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
    margin: auto;
  }

  #button_advanced:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  }

  /* Add a black background color to the top navigation */
  .topnav {
    background-color: #AD1B9E;
    overflow: hidden;
    min-width: 1000px;
  }

  /* Style the links inside the navigation bar */
  .topnav a {
    float: left;
    display: block;
    color: #EBC1EE;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }

  /* Change the color of links on hover */
  .topnav a:hover {
    background-color: #EBC1EE;
    color: #AD1B9E;
  }

  /* Add an active class to highlight the current page */
  .active {
    background-color: #EBC1EE;
    color: black;
  }

  /* Hide the link that should open and close the topnav on small screens */
  .topnav .icon {
    display: none;
  }

  #alpha {
    width: 600px;
    height: 80px;
    border-width: 2px;
    border-color: #ff28e9 #AD1B9E #AD1B9E #ff28e9;
    margin: auto;
  }

  #submit {
    width: 600px;
    background-color: #AD1B9E;
    border: none;
    border-color: #8F1383;
    color: #EBC1EE;
    height: 40px;
    margin: auto;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }

  #submit:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  }

  .container {
    position: relative;
    overflow: hidden;
    float: left;
  }

  #left {
    display: inline-block;
    float: left;
  }

  #myDiv {
    display: inline-block;
    float: right;
    margin: auto;
    overflow: hidden;
  }

  #table {
    display: inline-block;
    margin: auto;
    border-color: #ad1b9e;
    overflow: hidden;
    border-color: black;
    border-width: 2px
  }

</style>

<div class="topnav" id="myTopnav">
  <a href="#home">HOME</a>
  <a href="#about">ABOUT US</a>
  <a href="#create">CREATE</a>
  <a href="#learn">LEARN</a>
  <a href="#faq">FAQ</a>
  {% if user.username %}
    <a href="{% url 'graph:logout_user' %}" style="float:right">LOGOUT</a>
    <a href="#username" style="float:right">{{ user.username }}</a>
  {% else %}
    <a href="{% url 'graph:login' %}" style="float:right">LOGIN</a>
  {% endif %}
</div>

<br><br>

<div class="container">

  <div id="left" class="left">
    <form action="{% url 'graph:plot' %}" method="post" id="usrform">
      {% csrf_token %}
      <label for="alpha" id="text_for_alpha"><h3>Alpha: </h3></label>
      {% if form.is_valid %}
        <input id="alpha" type="text" name="alpha" value="{{ alpha }}">
      {% else %}
        <input id="alpha" type="text" name="alpha" value="">
      {% endif %}
      <br>
      <input id = "submit" type="submit" value="SUBMIT">
    </form>
  </div>

  {% if form.is_valid %}
    <br>

    <div class="table" id="table"></div>
    <script>

    var values = {{ values | safe }}

    var data = [{
      type: 'table',
      columnorder: [1,2,3,4,5,6,7],
      columnwidth: [25, 50, 50, 60, 60, 60, 60],
      header: {
        values: ['Year', 'IR', 'Sharpe Ratio', 'Turnover', 'Max Drawdown', 'Yearly Returns', 'Fitness'],
        align: ["left", "center"],
        line: {width: 0, color: '#506784'},
        fill: {color: '#ad1b9e'},
        font: {family: "Arial", size: 12, color: "white"}
      },
      cells: {
        values: values,
        align: ["left", "center"],
        line: {color: "#506784", width: 0},
        fill: {color: ['#EBC1EE']},
        font: {family: "Arial", size: 11, color: ["#506784"]}
      }
    }];

    var layout = {
      height: 230,
      width: 600,
      margin: {
        l: 0,
        r: 10,
        b: 0,
        t: 10,
        pad: 4
      }
    };

    Plotly.plot('table', data, layout);

    </script>

    <div class="advanced">
      <button type="button" id="button_advanced">ADVANCED</button>
    </div>

  </div>

    <div id="myDiv" class="graph"></div>

    <script>
    var data = [
      {
        x: {{ data_for_x | safe }},
        y: {{ data_for_y }},
        fill: 'tonexty',
        type: 'scatter',
        fillcolor: '#82CFFD',
        mode: 'lines',
        line: {
          color: '#82CFFD',
          width: 1.1
        },
      }];

      var layout = {
        height: 600,
        width: 800,
        margin: {
          l: 80,
          r: 30,
          b: 80,
          t: 30,
          pad: 4
        },
        opacity: 0.5,
      };

    Plotly.newPlot('myDiv', data, layout);

    </script>
    </div>

    <br>

    <script type="text/javascript">
        document.getElementById("button_advanced").onclick = function () {
            location.href = "shares";
        };
    </script>
  {% endif %}

graph/templates/graph/pnl.html
<head>
  <!-- Plotly.js -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<style>

  #button1, #button2 {
    background-color: #AD1B9E;
    border: none;
    color: #EBC1EE;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
    margin:auto;
  }

  #button1:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  }

  #table {
    margin-top: -15px;
    border-color: #ad1b9e;
  }

  /* Add a black background color to the top navigation */
  .topnav {
    background-color: #AD1B9E;
    overflow: hidden;
    min-width: 1000px;
  }

  /* Style the links inside the navigation bar */
  .topnav a {
    float: left;
    display: block;
    color: #EBC1EE;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }

  /* Change the color of links on hover */
  .topnav a:hover {
    background-color: #EBC1EE;
    color: #AD1B9E;
  }

  /* Add an active class to highlight the current page */
  .active {
    background-color: #EBC1EE;
    color: black;
  }

  /* Hide the link that should open and close the topnav on small screens */
  .topnav .icon {
    display: none;
  }

  #alpha {
    width: 800px;
    height: 80px;
    border-width: 2px;
    border-color: #ff28e9 #AD1B9E #AD1B9E #ff28e9;
    margin-left: 10px;
    margin-top: 20px;
  }

  #submit {
    width: 800px;
    background-color: #AD1B9E;
    border: none;
    border-color: #8F1383;
    color: #EBC1EE;
    height: 40px;
    margin-top: -2px;
    margin-left: 10px;
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }

  #submit:hover {
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  }

  .container {
    position: relative;
    overflow: hidden;
    margin-left: 85px;
  }

  @media screen and (max-width: 420px) {
  #button2 {
    margin-top: 10px;
  }
}

  #left {
    float: left;
  }

  #myDiv {
    float: right;
    width: 700px;
    height: 600px;
    margin-top: -65px;
    margin-right: -45px;
  }

  .contain {
    width: 600px;
    height: 600px;
  }

  .table {
    margin-left: 85px;
    overflow-x: scroll;
    width: 1300px;
  }

</style>

<div class="topnav" id="myTopnav">
  <a href="#home">HOME</a>
  <a href="#about">ABOUT US</a>
  <a href="#create">CREATE</a>
  <a href="#learn">LEARN</a>
  <a href="#faq">FAQ</a>
  {% if user.username %}
    <a href="{% url 'graph:logout_user' %}" style="float:right">LOGOUT</a>
    <a href="#username" style="float:right">{{ user.username }}</a>
  {% else %}
    <a href="{% url 'graph:login' %}" style="float:right">LOGIN</a>
  {% endif %}
</div>

<br>

<div class="container">
  <button type="button" id="button1">Positions</button>
  <button type="button" id="button2">PNL</button>
</div>

<br>
<div class="contain">
  <div class="table" id="table"></div>
</div>
<script>

var values = {{ values3 | safe }}
var header = {{ header3 | safe }}

var fillArray = function(value, len){
  var arr=[];
  for (var i=0 ; i<len-1; i++){
    arr.push(value);
  }
  arr.unshift(14);
  return arr;
};

var data = [{
  type: 'table',
  //columnorder: [1,2,3,4,5,6,7],
  //columnwidth: [40, 65, 65, 60, 60, 60, 60],
  columnwidth: fillArray(7,header.length-1),
  header: {
    values: header,
    align: ["center"],
    line: {width: 0, color: '#506784'},
    fill: {color: '#ad1b9e'},
    font: {family: "Arial", size: 12, color: "white"}
  },
  cells: {
    values: values,
    align: ["center"],
    line: {color: "#506784", width: 0},
    fill: {color: ['#EBC1EE']},
    font: {family: "Arial", size: 11, color: ["#506784"]}
  }
}];

var layout = {
  height: 600,
  width: 1600,
  margin: {
    l: 0,
    r: 10,
    b: 0,
    t: 10,
    pad: 4
  }
};

Plotly.plot('table', data, layout);

</script>

<script type="text/javascript">
    document.getElementById("button1").onclick = function () {
        location.href = "shares";
    };
    document.getElementById("button2").onclick = function () {
        location.href = "pnl";
    };
</script>